name: Update Experience Years

on:
  schedule:
    # Run every 6 months (January 1st and July 1st)
    - cron: '0 0 1 1,7 *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Update years of experience
        run: |
          cat > update_experience.py << 'EOL'
          import re
          import datetime
          
          CAREER_START = datetime.date(2020, 11, 15)
          
          today = datetime.date.today()
          experience_years = today.year - CAREER_START.year
          
          if (today.month, today.day) < (CAREER_START.month, CAREER_START.day):
              experience_years -= 1
              
          with open('README.md', 'r') as file:
              content = file.read()
              
          updated_content = re.sub(
              r'Full-stack developer with \d+\+ years of experience',
              f'Full-stack developer with {experience_years}+ years of experience',
              content
          )
          
          with open('README.md', 'w') as file:
              file.write(updated_content)
          EOL
          
          python update_experience.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update years of experience" && git push)